// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SAE401_API.Models.EntityFramework;

#nullable disable

namespace SAE401_API.Migrations
{
    [DbContext(typeof(_DBMilibooContext))]
    partial class _DBMilibooContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.HasSequence<int>("seq_adr");

            modelBuilder.HasSequence<int>("seq_avi");

            modelBuilder.HasSequence<int>("seq_car");

            modelBuilder.HasSequence<int>("seq_cli");

            modelBuilder.HasSequence<int>("seq_cmd");

            modelBuilder.HasSequence<int>("seq_msg");

            modelBuilder.HasSequence<int>("seq_pho");

            modelBuilder.HasSequence<int>("seq_pmt");

            modelBuilder.HasSequence<int>("seq_prd");

            modelBuilder.HasSequence<int>("seq_sga");

            modelBuilder.Entity("SAE401_API.Models.EntityFramework.Activitepro", b =>
                {
                    b.Property<int>("Idactivitepro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("act_idactivitepro");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Idactivitepro"));

                    b.Property<string>("Nomactivitepro")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("act_nomactivitepro");

                    b.HasKey("Idactivitepro")
                        .HasName("pk_act");

                    b.HasIndex(new[] { "Nomactivitepro" }, "ix_t_e_activitepro_act_nomactivitepro")
                        .IsUnique();

                    b.ToTable("t_e_activitepro_act");
                });

            modelBuilder.Entity("SAE401_API.Models.EntityFramework.Adresse", b =>
                {
                    b.Property<int>("Idadresse")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("adr_idadresse")
                        .HasDefaultValueSql("nextval('seq_adr')");

                    b.Property<string>("Codeinsee")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character(5)")
                        .HasColumnName("adr_codeinsee")
                        .IsFixedLength();

                    b.Property<string>("Codepostaladresse")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character(5)")
                        .HasColumnName("adr_codepostaladresse")
                        .IsFixedLength();

                    b.Property<int>("Idclient")
                        .HasColumnType("integer")
                        .HasColumnName("adr_idclient");

                    b.Property<int>("Iddepartement")
                        .HasColumnType("integer")
                        .HasColumnName("adr_iddepartement");

                    b.Property<int>("Idpays")
                        .HasColumnType("integer")
                        .HasColumnName("adr_idpays");

                    b.Property<string>("Nomadresse")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("adr_nomadresse");

                    b.Property<string>("Nomrue")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("adr_nomrue");

                    b.Property<string>("Numerorue")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("adr_numerorue");

                    b.HasKey("Idadresse")
                        .HasName("pk_adr");

                    b.HasIndex("Codeinsee");

                    b.HasIndex("Idclient");

                    b.HasIndex("Iddepartement");

                    b.HasIndex("Idpays");

                    b.ToTable("t_e_adresse_adr");
                });

            modelBuilder.Entity("SAE401_API.Models.EntityFramework.Aime", b =>
                {
                    b.Property<int>("Idclient")
                        .HasColumnType("integer")
                        .HasColumnName("aim_idclient");

                    b.Property<int>("Idproduit")
                        .HasColumnType("integer")
                        .HasColumnName("aim_idproduit");

                    b.HasKey("Idclient", "Idproduit")
                        .HasName("pk_aim");

                    b.HasIndex("Idproduit");

                    b.ToTable("t_j_aime_aim");
                });

            modelBuilder.Entity("SAE401_API.Models.EntityFramework.Attributproduit", b =>
                {
                    b.Property<int>("Idattribut")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("att_idattribut");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Idattribut"));

                    b.Property<int>("Idtypeproduit")
                        .HasColumnType("integer")
                        .HasColumnName("att_idtypeproduit");

                    b.Property<string>("Nomattribut")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("att_nomattribut");

                    b.HasKey("Idattribut")
                        .HasName("pk_att");

                    b.HasIndex(new[] { "Idtypeproduit", "Nomattribut" }, "ix_t_e_attributproduit_att_idtypeproduit_nomattribut")
                        .IsUnique();

                    b.ToTable("t_e_attributproduit_att");
                });

            modelBuilder.Entity("SAE401_API.Models.EntityFramework.Avisproduit", b =>
                {
                    b.Property<int>("Idavis")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("avi_idavis")
                        .HasDefaultValueSql("nextval('seq_avi')");

                    b.Property<string>("Commentaireavis")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("avi_commentaireavis");

                    b.Property<DateTime>("Dateavis")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("avi_dateavis")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("Idclient")
                        .HasColumnType("integer")
                        .HasColumnName("avi_idclient");

                    b.Property<int>("Idproduit")
                        .HasColumnType("integer")
                        .HasColumnName("avi_idproduit");

                    b.Property<int>("Noteavis")
                        .HasColumnType("integer")
                        .HasColumnName("avi_noteavis");

                    b.Property<string>("Reponsemiliboo")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("avi_reponsemiliboo");

                    b.HasKey("Idavis")
                        .HasName("pk_avi");

                    b.HasIndex("Idproduit");

                    b.HasIndex(new[] { "Idclient", "Idproduit" }, "ix_t_e_avisproduit_avi_idclient_idproduit")
                        .IsUnique();

                    b.ToTable("t_e_avisproduit_avi");
                });

            modelBuilder.Entity("SAE401_API.Models.EntityFramework.Cartebancaire", b =>
                {
                    b.Property<int>("Idcartebancaire")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("car_idcartebancaire")
                        .HasDefaultValueSql("nextval('seq_car')");

                    b.Property<DateTime>("Dateenregistement")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("car_dateenregistrement")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime>("Dateexpirationcarte")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("car_dateexpirationcarte");

                    b.Property<int>("Idclient")
                        .HasColumnType("integer")
                        .HasColumnName("car_idclient");

                    b.Property<string>("Nomcartebancaire")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("car_nomcartebancaire");

                    b.Property<string>("Numcartebancaire")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character(16)")
                        .HasColumnName("car_numcartebancaire")
                        .IsFixedLength();

                    b.Property<string>("Titulairecartebancaire")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("car_titulairecartebancaire");

                    b.HasKey("Idcartebancaire")
                        .HasName("pk_car");

                    b.HasIndex(new[] { "Idclient", "Nomcartebancaire" }, "ix_t_e_cartebancaire_car_idclient_nomcartebancaire")
                        .IsUnique();

                    b.HasIndex(new[] { "Idclient", "Numcartebancaire" }, "ix_t_e_cartebancaire_car_idclient_numcartebancaire")
                        .IsUnique();

                    b.ToTable("t_e_cartebancaire_car");
                });

            modelBuilder.Entity("SAE401_API.Models.EntityFramework.Categorieproduit", b =>
                {
                    b.Property<int>("Idcategorie")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("cat_idcategorie");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Idcategorie"));

                    b.Property<string>("Descriptioncategorie")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("cat_descriptioncategorie");

                    b.Property<bool>("Estfiltrable")
                        .HasColumnType("boolean")
                        .HasColumnName("cat_estfiltrable");

                    b.Property<int?>("IdcategorieParent")
                        .HasColumnType("integer")
                        .HasColumnName("cat_idcategorie2");

                    b.Property<int?>("Idphoto")
                        .HasColumnType("integer")
                        .HasColumnName("cat_idphoto");

                    b.Property<string>("Nomcategorie")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("cat_nomcategorie");

                    b.HasKey("Idcategorie")
                        .HasName("pk_cat");

                    b.HasIndex("IdcategorieParent");

                    b.HasIndex("Idphoto");

                    b.HasIndex(new[] { "Nomcategorie" }, "ix_t_e_categorieproduit_cat_nomcategorie")
                        .IsUnique();

                    b.ToTable("t_e_categorieproduit_cat");
                });

            modelBuilder.Entity("SAE401_API.Models.EntityFramework.Client", b =>
                {
                    b.Property<int>("Idclient")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("cli_idclient")
                        .HasDefaultValueSql("nextval('seq_cli')");

                    b.Property<char?>("Civiliteclient")
                        .HasColumnType("character(1)")
                        .HasColumnName("cli_civiliteclient");

                    b.Property<DateTime?>("Datecreationcompte")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cli_datecreationcompte")
                        .HasDefaultValueSql("now()")
                        .IsFixedLength();

                    b.Property<string>("Emailclient")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("cli_emailclient");

                    b.Property<string>("Hashmdp")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character(256)")
                        .HasColumnName("cli_hashmdp")
                        .IsFixedLength();

                    b.Property<bool>("Newslettermiliboo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("cli_newslettermiliboo");

                    b.Property<bool>("Newsletterpartenaires")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("cli_newsletterpartenaires");

                    b.Property<string>("Nomclient")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("cli_nomclient");

                    b.Property<int>("Pointfideliteclient")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("cli_pointfideliteclient");

                    b.Property<string>("Prenomclient")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("cli_prenomclient");

                    b.Property<string>("Telfixeclient")
                        .HasMaxLength(11)
                        .HasColumnType("character(11)")
                        .HasColumnName("cli_telfixeclient")
                        .IsFixedLength();

                    b.Property<string>("Telportableclient")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("character(11)")
                        .HasColumnName("cli_telportableclient")
                        .IsFixedLength();

                    b.HasKey("Idclient")
                        .HasName("pk_cli");

                    b.HasIndex(new[] { "Nomclient", "Prenomclient", "Telportableclient" }, "ix_t_e_client_cli_nomclient_prenomclient_telportableclient")
                        .IsUnique();

                    b.ToTable("t_e_client_cli");
                });

            modelBuilder.Entity("SAE401_API.Models.EntityFramework.Codepromo", b =>
                {
                    b.Property<int>("Idcodepromo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("cod_idcodepromo");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Idcodepromo"));

                    b.Property<DateTime?>("Dateexpirationcode")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cod_dateexpirationcode");

                    b.Property<bool>("Estvalide")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("cod_estvalide");

                    b.Property<int?>("Idclient")
                        .HasColumnType("integer")
                        .HasColumnName("cod_idclient");

                    b.Property<string>("Nomcodepromo")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("cod_nomcodepromo");

                    b.Property<decimal>("Valeurreduction")
                        .HasColumnType("numeric(5, 2)")
                        .HasColumnName("cod_valeurreduction");

                    b.HasKey("Idcodepromo")
                        .HasName("pk_cod");

                    b.HasIndex("Idclient");

                    b.ToTable("t_e_codepromo_cod");
                });

            modelBuilder.Entity("SAE401_API.Models.EntityFramework.Coloration", b =>
                {
                    b.Property<int>("Idproduit")
                        .HasColumnType("integer")
                        .HasColumnName("col_idproduit");

                    b.Property<int>("Idcouleur")
                        .HasColumnType("integer")
                        .HasColumnName("col_idcouleur");

                    b.Property<string>("Descriptioncoloration")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("col_descriptioncoloration");

                    b.Property<bool>("Estvisible")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("col_estvisible");

                    b.Property<decimal?>("Prixsolde")
                        .HasColumnType("numeric(10, 2)")
                        .HasColumnName("col_prixsolde");

                    b.Property<decimal>("Prixvente")
                        .HasColumnType("numeric(10, 2)")
                        .HasColumnName("col_prixvente");

                    b.Property<int>("Quantitestock")
                        .HasColumnType("integer")
                        .HasColumnName("col_quantitestock");

                    b.HasKey("Idproduit", "Idcouleur")
                        .HasName("pk_col");

                    b.HasIndex("Idcouleur");

                    b.ToTable("t_j_coloration_col");
                });

            modelBuilder.Entity("SAE401_API.Models.EntityFramework.Commande", b =>
                {
                    b.Property<int>("Idcommande")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("cmd_idcommande")
                        .HasDefaultValueSql("nextval('seq_cmd')");

                    b.Property<bool>("Avecassurance")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("cmd_avecassurance");

                    b.Property<bool>("Aveclivraisonexpress")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("cmd_aveclivraisonexpress");

                    b.Property<DateTime>("Datecommande")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cmd_datecommande")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("IdadresseFact")
                        .HasColumnType("integer")
                        .HasColumnName("cmd_adr_idadresse");

                    b.Property<int>("IdadresseLivr")
                        .HasColumnType("integer")
                        .HasColumnName("cmd_idadresse");

                    b.Property<int>("Idclient")
                        .HasColumnType("integer")
                        .HasColumnName("cmd_idclient");

                    b.Property<int?>("Idcodepromo")
                        .HasColumnType("integer")
                        .HasColumnName("cmd_idcodepromo");

                    b.Property<int>("Idstatut")
                        .HasColumnType("integer")
                        .HasColumnName("cmd_idstatut");

                    b.Property<int>("Idtransporteur")
                        .HasColumnType("integer")
                        .HasColumnName("cmd_idtransporteur");

                    b.Property<string>("Instructionlivraison")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("cmd_instructionlivraison");

                    b.HasKey("Idcommande")
                        .HasName("pk_cmd");

                    b.HasIndex("IdadresseFact");

                    b.HasIndex("IdadresseLivr");

                    b.HasIndex("Idclient");

                    b.HasIndex("Idcodepromo");

                    b.HasIndex("Idstatut");

                    b.HasIndex("Idtransporteur");

                    b.ToTable("t_e_commande_cmd");
                });

            modelBuilder.Entity("SAE401_API.Models.EntityFramework.Commandecomposition", b =>
                {
                    b.Property<int>("Idcomposition")
                        .HasColumnType("integer")
                        .HasColumnName("cmc_idcomposition");

                    b.Property<int>("Idcommande")
                        .HasColumnType("integer")
                        .HasColumnName("cmc_idcommande");

                    b.Property<int>("Quantitecompositioncommande")
                        .HasColumnType("integer")
                        .HasColumnName("cmc_quantitecompositioncommande");

                    b.HasKey("Idcomposition", "Idcommande")
                        .HasName("pk_cmc");

                    b.HasIndex("Idcommande");

                    b.ToTable("t_j_commandecomposition_cmc");
                });

            modelBuilder.Entity("SAE401_API.Models.EntityFramework.Compositionproduit", b =>
                {
                    b.Property<int>("Idcomposition")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("cmp_idcomposition");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Idcomposition"));

                    b.Property<string>("Descriptioncomposition")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("cmp_descriptioncomposition");

                    b.Property<string>("Nomcomposition")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("cmp_nomcomposition");

                    b.Property<decimal?>("Prixsoldecomposition")
                        .HasColumnType("numeric(10, 2)")
                        .HasColumnName("cmp_prixsoldecomposition");

                    b.Property<decimal>("Prixventecomposition")
                        .HasColumnType("numeric(10, 2)")
                        .HasColumnName("cmp_prixventecomposition");

                    b.HasKey("Idcomposition")
                        .HasName("pk_cmp");

                    b.HasIndex(new[] { "Nomcomposition" }, "ix_t_e_compositionproduit_cmp_nomcomposition")
                        .IsUnique();

                    b.ToTable("t_e_compositionproduit_cmp");
                });

            modelBuilder.Entity("SAE401_API.Models.EntityFramework.Couleur", b =>
                {
                    b.Property<int>("Idcouleur")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("cou_idcouleur");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Idcouleur"));

                    b.Property<string>("Nomcouleur")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("cou_nomcouleur");

                    b.Property<string>("Rgbcouleur")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("character(6)")
                        .HasColumnName("cou_rgbcouleur")
                        .IsFixedLength();

                    b.HasKey("Idcouleur")
                        .HasName("pk_cou");

                    b.HasIndex(new[] { "Nomcouleur" }, "ix_t_e_couleur_cou_nomcouleur")
                        .IsUnique();

                    b.ToTable("t_e_couleur_cou");
                });

            modelBuilder.Entity("SAE401_API.Models.EntityFramework.Departement", b =>
                {
                    b.Property<int>("Iddepartement")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("dep_iddepartement");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Iddepartement"));

                    b.Property<string>("Nomdepartement")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("dep_nomdepartement");

                    b.HasKey("Iddepartement")
                        .HasName("pk_dep");

                    b.ToTable("t_e_departement_dep");
                });

            modelBuilder.Entity("SAE401_API.Models.EntityFramework.Detailcommande", b =>
                {
                    b.Property<int>("Idproduit")
                        .HasColumnType("integer")
                        .HasColumnName("dcm_idproduit");

                    b.Property<int>("Idcouleur")
                        .HasColumnType("integer")
                        .HasColumnName("dcm_idcouleur");

                    b.Property<int>("Idcommande")
                        .HasColumnType("integer")
                        .HasColumnName("dcm_idcommande");

                    b.Property<int>("Quantitecommande")
                        .HasColumnType("integer")
                        .HasColumnName("dcm_quantitecommande");

                    b.HasKey("Idproduit", "Idcouleur", "Idcommande")
                        .HasName("pk_dcm");

                    b.HasIndex("Idcommande");

                    b.ToTable("t_j_detailcommande_dcm");
                });

            modelBuilder.Entity("SAE401_API.Models.EntityFramework.Detailcomposition", b =>
                {
                    b.Property<int>("Idproduit")
                        .HasColumnType("integer")
                        .HasColumnName("dcp_idproduit");

                    b.Property<int>("Idcouleur")
                        .HasColumnType("integer")
                        .HasColumnName("dcp_idcouleur");

                    b.Property<int>("Idcomposition")
                        .HasColumnType("integer")
                        .HasColumnName("dcp_idcomposition");

                    b.Property<int>("Quantitecomposition")
                        .HasColumnType("integer")
                        .HasColumnName("dcp_quantitecomposition");

                    b.HasKey("Idproduit", "Idcouleur", "Idcomposition")
                        .HasName("pk_dcp");

                    b.HasIndex("Idcomposition");

                    b.ToTable("t_j_detailcomposition_dcp");
                });

            modelBuilder.Entity("SAE401_API.Models.EntityFramework.Detailpanier", b =>
                {
                    b.Property<int>("Idproduit")
                        .HasColumnType("integer")
                        .HasColumnName("dpn_idproduit");

                    b.Property<int>("Idcouleur")
                        .HasColumnType("integer")
                        .HasColumnName("dpn_idcouleur");

                    b.Property<int>("Idclient")
                        .HasColumnType("integer")
                        .HasColumnName("dpn_idclient");

                    b.Property<int>("Quantitepanier")
                        .HasColumnType("integer")
                        .HasColumnName("dpn_quantitepanier");

                    b.HasKey("Idproduit", "Idcouleur", "Idclient")
                        .HasName("pk_dpn");

                    b.HasIndex("Idclient");

                    b.ToTable("t_j_detailpanier_dpn");
                });

            modelBuilder.Entity("SAE401_API.Models.EntityFramework.Detailpaniercomposition", b =>
                {
                    b.Property<int>("Idcomposition")
                        .HasColumnType("integer")
                        .HasColumnName("dpc_idcomposition");

                    b.Property<int>("Idclient")
                        .HasColumnType("integer")
                        .HasColumnName("dpc_idclient");

                    b.Property<int>("Quantitepaniercomposition")
                        .HasColumnType("integer")
                        .HasColumnName("dpc_quantitepaniercomposition");

                    b.HasKey("Idcomposition", "Idclient")
                        .HasName("pk_dpc");

                    b.HasIndex("Idclient");

                    b.ToTable("t_j_detailpaniercomposition_dpc");
                });

            modelBuilder.Entity("SAE401_API.Models.EntityFramework.Detailregroupement", b =>
                {
                    b.Property<int>("Idproduit")
                        .HasColumnType("integer")
                        .HasColumnName("drg_idproduit");

                    b.Property<int>("Idcouleur")
                        .HasColumnType("integer")
                        .HasColumnName("drg_idcouleur");

                    b.Property<int>("Idregroupement")
                        .HasColumnType("integer")
                        .HasColumnName("drg_idregroupement");

                    b.HasKey("Idproduit", "Idcouleur", "Idregroupement")
                        .HasName("pk_drg");

                    b.HasIndex("Idregroupement");

                    b.ToTable("t_j_detailregroupement_drg");
                });

            modelBuilder.Entity("SAE401_API.Models.EntityFramework.Historiqueconsultation", b =>
                {
                    b.Property<int>("Idclient")
                        .HasColumnType("integer")
                        .HasColumnName("hst_idclient");

                    b.Property<int>("Idproduit")
                        .HasColumnType("integer")
                        .HasColumnName("hst_idproduit");

                    b.Property<DateTime>("Dateconsultation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("hst_dateconsultation")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Idclient", "Idproduit")
                        .HasName("pk_hst");

                    b.HasIndex("Idproduit");

                    b.ToTable("t_j_historiqueconsultation_hst");
                });

            modelBuilder.Entity("SAE401_API.Models.EntityFramework.Messagechatbot", b =>
                {
                    b.Property<int>("Idmessage")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("msg_idmessage")
                        .HasDefaultValueSql("nextval('seq_msg')");

                    b.Property<string>("Contenumessage")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("msg_contenumessage");

                    b.Property<int>("Idclient")
                        .HasColumnType("integer")
                        .HasColumnName("msg_idclient");

                    b.Property<string>("Reponsemessage")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("msg_reponsemessage");

                    b.HasKey("Idmessage")
                        .HasName("pk_msg");

                    b.HasIndex("Idclient");

                    b.ToTable("t_e_messagechatbot_msg");
                });

            modelBuilder.Entity("SAE401_API.Models.EntityFramework.Paiement", b =>
                {
                    b.Property<int>("Idpaiement")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("pmt_idpaiement")
                        .HasDefaultValueSql("nextval('seq_pmt')");

                    b.Property<DateTime>("Datepaiement")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("pmt_datepaiement")
                        .HasDefaultValueSql("now()");

                    b.Property<int?>("Idcartebancaire")
                        .HasColumnType("integer")
                        .HasColumnName("pmt_idcartebancaire");

                    b.Property<int>("Idcommande")
                        .HasColumnType("integer")
                        .HasColumnName("pmt_idcommande");

                    b.Property<int>("Idtypepaiement")
                        .HasColumnType("integer")
                        .HasColumnName("pmt_idtypepaiement");

                    b.Property<string>("Indicepaiement")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("pmt_indicepaiement");

                    b.Property<decimal>("Montantpaiement")
                        .HasColumnType("numeric(10, 2)")
                        .HasColumnName("pmt_montantpaiement");

                    b.HasKey("Idpaiement")
                        .HasName("pk_pmt");

                    b.HasIndex("Idcartebancaire");

                    b.HasIndex("Idcommande");

                    b.HasIndex("Idtypepaiement");

                    b.ToTable("t_e_paiement_pmt");
                });

            modelBuilder.Entity("SAE401_API.Models.EntityFramework.Pay", b =>
                {
                    b.Property<int>("Idpays")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("pay_idpays");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Idpays"));

                    b.Property<string>("Nompays")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("pay_nompays");

                    b.HasKey("Idpays")
                        .HasName("pk_pay");

                    b.HasIndex(new[] { "Nompays" }, "ix_t_e_pays_pay_nompays")
                        .IsUnique();

                    b.ToTable("t_e_pays_pay");
                });

            modelBuilder.Entity("SAE401_API.Models.EntityFramework.Photo", b =>
                {
                    b.Property<int>("Idphoto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("pho_idphoto")
                        .HasDefaultValueSql("nextval('seq_pho')");

                    b.Property<string>("Descriptionphoto")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("pho_descriptionphoto");

                    b.Property<string>("Sourcephoto")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("pho_sourcephoto");

                    b.HasKey("Idphoto")
                        .HasName("pk_pho");

                    b.ToTable("t_e_photo_pho");
                });

            modelBuilder.Entity("SAE401_API.Models.EntityFramework.Photoavi", b =>
                {
                    b.Property<int>("Idavis")
                        .HasColumnType("integer")
                        .HasColumnName("pav_idavis");

                    b.Property<int>("Idphoto")
                        .HasColumnType("integer")
                        .HasColumnName("pav_idproduit");

                    b.HasKey("Idavis", "Idphoto")
                        .HasName("pk_pav");

                    b.HasIndex("Idphoto");

                    b.ToTable("t_j_photoavis_pav");
                });

            modelBuilder.Entity("SAE401_API.Models.EntityFramework.Photocoloration", b =>
                {
                    b.Property<int>("Idproduit")
                        .HasColumnType("integer")
                        .HasColumnName("pco_idproduit");

                    b.Property<int>("Idcouleur")
                        .HasColumnType("integer")
                        .HasColumnName("pco_idcouleur");

                    b.Property<int>("Idphoto")
                        .HasColumnType("integer")
                        .HasColumnName("pco_idphoto");

                    b.HasKey("Idproduit", "Idcouleur", "Idphoto")
                        .HasName("pk_pco");

                    b.HasIndex("Idphoto");

                    b.ToTable("t_j_photocoloration_pco");
                });

            modelBuilder.Entity("SAE401_API.Models.EntityFramework.Produit", b =>
                {
                    b.Property<int>("Idproduit")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("prd_idproduit")
                        .HasDefaultValueSql("nextval('seq_prd')");

                    b.Property<string>("Aspecttechnique")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("prd_aspecttechnique");

                    b.Property<decimal>("Coutlivraison")
                        .HasColumnType("numeric(10, 2)")
                        .HasColumnName("prd_coutlivraison");

                    b.Property<int>("Delailivraison")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(72)
                        .HasColumnName("prd_delailivraison");

                    b.Property<int>("Idpays")
                        .HasColumnType("integer")
                        .HasColumnName("prd_idpays");

                    b.Property<int>("Idtypeproduit")
                        .HasColumnType("integer")
                        .HasColumnName("prd_idtypeproduit");

                    b.Property<int>("Nbpaiementmax")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("prd_nbpaiementmax");

                    b.Property<string>("Nomproduit")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("prd_nomproduit");

                    b.Property<string>("Notice")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("prd_notice");

                    b.HasKey("Idproduit")
                        .HasName("pk_prd");

                    b.HasIndex("Idpays");

                    b.HasIndex("Idtypeproduit");

                    b.HasIndex(new[] { "Nomproduit" }, "ix_t_e_produit_prd_nomproduit")
                        .IsUnique();

                    b.ToTable("t_e_produit_prd");
                });

            modelBuilder.Entity("SAE401_API.Models.EntityFramework.Produitsimilaire", b =>
                {
                    b.Property<int>("IdproduitSim")
                        .HasColumnType("integer")
                        .HasColumnName("pds_idproduit2");

                    b.Property<int>("IdproduitRef")
                        .HasColumnType("integer")
                        .HasColumnName("pds_idproduit");

                    b.HasKey("IdproduitSim", "IdproduitRef")
                        .HasName("pk_pds");

                    b.HasIndex("IdproduitRef");

                    b.ToTable("t_j_produitsimilaire_pds");
                });

            modelBuilder.Entity("SAE401_API.Models.EntityFramework.Professionel", b =>
                {
                    b.Property<int>("Idclient")
                        .HasColumnType("integer")
                        .HasColumnName("pro_idclient");

                    b.Property<int>("Idactivitepro")
                        .HasColumnType("integer")
                        .HasColumnName("pro_idactivitepro");

                    b.Property<string>("Nomsociete")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("pro_nomsociete");

                    b.Property<string>("Numtva")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("character(11)")
                        .HasColumnName("pro_numtva")
                        .IsFixedLength();

                    b.HasKey("Idclient")
                        .HasName("pk_pro");

                    b.HasIndex("Idactivitepro");

                    b.ToTable("t_h_professionel_pro");
                });

            modelBuilder.Entity("SAE401_API.Models.EntityFramework.Regroupementproduit", b =>
                {
                    b.Property<int>("Idregroupement")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("rgp_idregroupement");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Idregroupement"));

                    b.Property<string>("Nomregroupement")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("rgp_nomregroupement");

                    b.HasKey("Idregroupement")
                        .HasName("pk_rgp");

                    b.HasIndex(new[] { "Nomregroupement" }, "ix_t_e_regroupementproduit_rgp_nomregroupement")
                        .IsUnique();

                    b.ToTable("t_e_regroupementproduit_rgp");
                });

            modelBuilder.Entity("SAE401_API.Models.EntityFramework.Signalementavi", b =>
                {
                    b.Property<int>("Idsignalement")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("sga_idsignalement")
                        .HasDefaultValueSql("nextval('seq_sga')");

                    b.Property<string>("Contenusignalement")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("sga_contenusignalement");

                    b.Property<DateTime>("Datesignalement")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sga_datesignalement")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Emailsignalement")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("sga_emailsignalement");

                    b.Property<int>("Idavis")
                        .HasColumnType("integer")
                        .HasColumnName("sga_idavis");

                    b.Property<int>("Idtypesignalement")
                        .HasColumnType("integer")
                        .HasColumnName("sga_idtypesignalement");

                    b.HasKey("Idsignalement")
                        .HasName("pk_sga");

                    b.HasIndex("Idtypesignalement");

                    b.HasIndex(new[] { "Idavis", "Emailsignalement" }, "ix_t_e_signalementavis_sga_idavis_emailsignalement")
                        .IsUnique();

                    b.ToTable("t_e_signalementavis_sga");
                });

            modelBuilder.Entity("SAE401_API.Models.EntityFramework.Statutcommande", b =>
                {
                    b.Property<int>("Idstatut")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("scd_idstatut");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Idstatut"));

                    b.Property<string>("Nomstatut")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("scd_nomstatut");

                    b.HasKey("Idstatut")
                        .HasName("pk_scd");

                    b.HasIndex(new[] { "Nomstatut" }, "ix_t_e_statutcommande_scd_nomstatut")
                        .IsUnique();

                    b.ToTable("t_e_statutcommande_scd");
                });

            modelBuilder.Entity("SAE401_API.Models.EntityFramework.Transporteur", b =>
                {
                    b.Property<int>("Idtransporteur")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("tpt_idtransporteur");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Idtransporteur"));

                    b.Property<string>("Nomtransporteur")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("tpt_nomtransporteur");

                    b.HasKey("Idtransporteur")
                        .HasName("pk_tpt");

                    b.HasIndex(new[] { "Nomtransporteur" }, "ix_t_e_transporteur_tpt_nomtransporteur")
                        .IsUnique();

                    b.ToTable("t_e_transporteur_tpt");
                });

            modelBuilder.Entity("SAE401_API.Models.EntityFramework.Typepaiement", b =>
                {
                    b.Property<int>("Idtypepaiement")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("tpm_idtypepaiement");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Idtypepaiement"));

                    b.Property<string>("Nomtypepaiement")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("tpm_nomtypepaiement");

                    b.HasKey("Idtypepaiement")
                        .HasName("pk_tpm");

                    b.HasIndex(new[] { "Nomtypepaiement" }, "ix_t_e_typepaiement_tpm_nomtypepaiement")
                        .IsUnique();

                    b.ToTable("t_e_typepaiement_tpm");
                });

            modelBuilder.Entity("SAE401_API.Models.EntityFramework.Typeproduit", b =>
                {
                    b.Property<int>("Idtypeproduit")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("tpd_idtypeproduit");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Idtypeproduit"));

                    b.Property<int>("Idcategorie")
                        .HasColumnType("integer")
                        .HasColumnName("tpd_idcategorie");

                    b.Property<string>("Nomtypeproduit")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("tpd_nomtypeproduit");

                    b.HasKey("Idtypeproduit")
                        .HasName("pk_tpd");

                    b.HasIndex("Idcategorie");

                    b.HasIndex(new[] { "Nomtypeproduit" }, "ix_t_e_typeproduit_tpd_nomtypeproduit")
                        .IsUnique();

                    b.ToTable("t_e_typeproduit_tpd");
                });

            modelBuilder.Entity("SAE401_API.Models.EntityFramework.Typesignalement", b =>
                {
                    b.Property<int>("Idtypesignalement")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("tsg_idtypesignalement");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Idtypesignalement"));

                    b.Property<string>("Nomtypesignalement")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("tsg_nomtypesignalement");

                    b.HasKey("Idtypesignalement")
                        .HasName("pk_tsg");

                    b.HasIndex(new[] { "Nomtypesignalement" }, "ix_t_e_typesignalement_tsg_nomtypesignalement")
                        .IsUnique();

                    b.ToTable("t_e_typesignalement_tsg");
                });

            modelBuilder.Entity("SAE401_API.Models.EntityFramework.Valeurattribut", b =>
                {
                    b.Property<int>("Idattribut")
                        .HasColumnType("integer")
                        .HasColumnName("val_idattribut");

                    b.Property<int>("Idproduit")
                        .HasColumnType("integer")
                        .HasColumnName("val_idproduit");

                    b.Property<string>("Valeur")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("val_valeur");

                    b.HasKey("Idattribut", "Idproduit")
                        .HasName("pk_val");

                    b.HasIndex("Idproduit");

                    b.ToTable("t_j_valeurattribut_val");
                });

            modelBuilder.Entity("SAE401_API.Models.EntityFramework.Ville", b =>
                {
                    b.Property<string>("Codeinsee")
                        .HasMaxLength(5)
                        .HasColumnType("character(5)")
                        .HasColumnName("vil_codeinsee")
                        .IsFixedLength();

                    b.Property<string>("Nomville")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("vil_nomville");

                    b.HasKey("Codeinsee")
                        .HasName("pk_vil");

                    b.ToTable("t_e_ville_vil");
                });

            modelBuilder.Entity("SAE401_API.Models.EntityFramework.Adresse", b =>
                {
                    b.HasOne("SAE401_API.Models.EntityFramework.Ville", "VilleNavigation")
                        .WithMany("AdressesNavigation")
                        .HasForeignKey("Codeinsee")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_adr_vil");

                    b.HasOne("SAE401_API.Models.EntityFramework.Client", "ClientNavigation")
                        .WithMany("AdressesNavigation")
                        .HasForeignKey("Idclient")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_adr_cli");

                    b.HasOne("SAE401_API.Models.EntityFramework.Departement", "DepartementNavigation")
                        .WithMany("AdressesNavigation")
                        .HasForeignKey("Iddepartement")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_adr_dep");

                    b.HasOne("SAE401_API.Models.EntityFramework.Pay", "PayNavigation")
                        .WithMany("AdressesNavigation")
                        .HasForeignKey("Idpays")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_adr_pay");

                    b.Navigation("ClientNavigation");

                    b.Navigation("DepartementNavigation");

                    b.Navigation("PayNavigation");

                    b.Navigation("VilleNavigation");
                });

            modelBuilder.Entity("SAE401_API.Models.EntityFramework.Aime", b =>
                {
                    b.HasOne("SAE401_API.Models.EntityFramework.Client", "ClientNavigation")
                        .WithMany("AimesNavigation")
                        .HasForeignKey("Idclient")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_aim_cli");

                    b.HasOne("SAE401_API.Models.EntityFramework.Produit", "ProduitNavigation")
                        .WithMany("AimesNavigation")
                        .HasForeignKey("Idproduit")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_aim_prd");

                    b.Navigation("ClientNavigation");

                    b.Navigation("ProduitNavigation");
                });

            modelBuilder.Entity("SAE401_API.Models.EntityFramework.Attributproduit", b =>
                {
                    b.HasOne("SAE401_API.Models.EntityFramework.Typeproduit", "TypeproduitNavigation")
                        .WithMany("AttributsNavigation")
                        .HasForeignKey("Idtypeproduit")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_att_tpd");

                    b.Navigation("TypeproduitNavigation");
                });

            modelBuilder.Entity("SAE401_API.Models.EntityFramework.Avisproduit", b =>
                {
                    b.HasOne("SAE401_API.Models.EntityFramework.Client", "ClientNavigation")
                        .WithMany("AvisNavigation")
                        .HasForeignKey("Idclient")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_avi_cli");

                    b.HasOne("SAE401_API.Models.EntityFramework.Produit", "ProduitNavigation")
                        .WithMany("AvisNavigation")
                        .HasForeignKey("Idproduit")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_avi_prd");

                    b.Navigation("ClientNavigation");

                    b.Navigation("ProduitNavigation");
                });

            modelBuilder.Entity("SAE401_API.Models.EntityFramework.Cartebancaire", b =>
                {
                    b.HasOne("SAE401_API.Models.EntityFramework.Client", "ClientNavigation")
                        .WithMany("CartesNavigation")
                        .HasForeignKey("Idclient")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_car_cli");

                    b.Navigation("ClientNavigation");
                });

            modelBuilder.Entity("SAE401_API.Models.EntityFramework.Categorieproduit", b =>
                {
                    b.HasOne("SAE401_API.Models.EntityFramework.Categorieproduit", "CategorieParenteNavigation")
                        .WithMany("CategorieEnfanteNavigation")
                        .HasForeignKey("IdcategorieParent")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_cat_cat");

                    b.HasOne("SAE401_API.Models.EntityFramework.Photo", "PhotoNavigation")
                        .WithMany("CategoriesNavigation")
                        .HasForeignKey("Idphoto")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_cat_pho");

                    b.Navigation("CategorieParenteNavigation");

                    b.Navigation("PhotoNavigation");
                });

            modelBuilder.Entity("SAE401_API.Models.EntityFramework.Codepromo", b =>
                {
                    b.HasOne("SAE401_API.Models.EntityFramework.Client", "ClientNavigation")
                        .WithMany("CodesNavigation")
                        .HasForeignKey("Idclient")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_cod_cli");

                    b.Navigation("ClientNavigation");
                });

            modelBuilder.Entity("SAE401_API.Models.EntityFramework.Coloration", b =>
                {
                    b.HasOne("SAE401_API.Models.EntityFramework.Couleur", "CouleurNavigation")
                        .WithMany("ColorationsNavigation")
                        .HasForeignKey("Idcouleur")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_col_cou");

                    b.HasOne("SAE401_API.Models.EntityFramework.Produit", "ProduitNavigation")
                        .WithMany("ColorationsNavigation")
                        .HasForeignKey("Idproduit")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_col_prd");

                    b.Navigation("CouleurNavigation");

                    b.Navigation("ProduitNavigation");
                });

            modelBuilder.Entity("SAE401_API.Models.EntityFramework.Commande", b =>
                {
                    b.HasOne("SAE401_API.Models.EntityFramework.Adresse", "AdresseFactNavigation")
                        .WithMany("CommandeFactNavigation")
                        .HasForeignKey("IdadresseFact")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_cmd_adr");

                    b.HasOne("SAE401_API.Models.EntityFramework.Adresse", "AdresseLivrNavigation")
                        .WithMany("CommandeLivrNavigation")
                        .HasForeignKey("IdadresseLivr")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_cmd_adr2");

                    b.HasOne("SAE401_API.Models.EntityFramework.Client", "ClientNavigation")
                        .WithMany("CommandesNavigation")
                        .HasForeignKey("Idclient")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_cmd_cli");

                    b.HasOne("SAE401_API.Models.EntityFramework.Codepromo", "CodeNavigation")
                        .WithMany("CommandesNavigation")
                        .HasForeignKey("Idcodepromo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_cmd_cod");

                    b.HasOne("SAE401_API.Models.EntityFramework.Statutcommande", "StatutNavigation")
                        .WithMany("CommandesNavigation")
                        .HasForeignKey("Idstatut")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_cmd_scd");

                    b.HasOne("SAE401_API.Models.EntityFramework.Transporteur", "TransporteurNavigation")
                        .WithMany("CommandesNavigation")
                        .HasForeignKey("Idtransporteur")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_cmd_tpt");

                    b.Navigation("AdresseFactNavigation");

                    b.Navigation("AdresseLivrNavigation");

                    b.Navigation("ClientNavigation");

                    b.Navigation("CodeNavigation");

                    b.Navigation("StatutNavigation");

                    b.Navigation("TransporteurNavigation");
                });

            modelBuilder.Entity("SAE401_API.Models.EntityFramework.Commandecomposition", b =>
                {
                    b.HasOne("SAE401_API.Models.EntityFramework.Commande", "CommandeNavigation")
                        .WithMany("DetailsCompositionNavigation")
                        .HasForeignKey("Idcommande")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_cmc_cmd");

                    b.HasOne("SAE401_API.Models.EntityFramework.Compositionproduit", "CompositionNavigation")
                        .WithMany("CommandesNavigation")
                        .HasForeignKey("Idcomposition")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_cmd_cmp");

                    b.Navigation("CommandeNavigation");

                    b.Navigation("CompositionNavigation");
                });

            modelBuilder.Entity("SAE401_API.Models.EntityFramework.Detailcommande", b =>
                {
                    b.HasOne("SAE401_API.Models.EntityFramework.Commande", "CommandeNavigation")
                        .WithMany("DetailsProduitNavigation")
                        .HasForeignKey("Idcommande")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_dcm_cmd");

                    b.HasOne("SAE401_API.Models.EntityFramework.Coloration", "ColorationNavigation")
                        .WithMany("DetailsCommandeNavigation")
                        .HasForeignKey("Idproduit", "Idcouleur")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_dcm_col");

                    b.Navigation("ColorationNavigation");

                    b.Navigation("CommandeNavigation");
                });

            modelBuilder.Entity("SAE401_API.Models.EntityFramework.Detailcomposition", b =>
                {
                    b.HasOne("SAE401_API.Models.EntityFramework.Compositionproduit", "CompositionNavigation")
                        .WithMany("DetailsNavigation")
                        .HasForeignKey("Idcomposition")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_dcp_cmp");

                    b.HasOne("SAE401_API.Models.EntityFramework.Coloration", "ColorationNavigation")
                        .WithMany("DetailsCompositionNavigation")
                        .HasForeignKey("Idproduit", "Idcouleur")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_dcp_col");

                    b.Navigation("ColorationNavigation");

                    b.Navigation("CompositionNavigation");
                });

            modelBuilder.Entity("SAE401_API.Models.EntityFramework.Detailpanier", b =>
                {
                    b.HasOne("SAE401_API.Models.EntityFramework.Client", "ClientNavigation")
                        .WithMany("PaniersProduitNavigation")
                        .HasForeignKey("Idclient")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_dpn_cli");

                    b.HasOne("SAE401_API.Models.EntityFramework.Coloration", "ColorationNavigation")
                        .WithMany("DetailsPanierNavigation")
                        .HasForeignKey("Idproduit", "Idcouleur")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_dpn_col");

                    b.Navigation("ClientNavigation");

                    b.Navigation("ColorationNavigation");
                });

            modelBuilder.Entity("SAE401_API.Models.EntityFramework.Detailpaniercomposition", b =>
                {
                    b.HasOne("SAE401_API.Models.EntityFramework.Client", "ClientNavigation")
                        .WithMany("PaniersCompositionNavigation")
                        .HasForeignKey("Idclient")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_dpc_cli");

                    b.HasOne("SAE401_API.Models.EntityFramework.Compositionproduit", "CompositionNavigation")
                        .WithMany("PaniersNavigation")
                        .HasForeignKey("Idcomposition")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_dpc_col");

                    b.Navigation("ClientNavigation");

                    b.Navigation("CompositionNavigation");
                });

            modelBuilder.Entity("SAE401_API.Models.EntityFramework.Detailregroupement", b =>
                {
                    b.HasOne("SAE401_API.Models.EntityFramework.Regroupementproduit", "RegroupementNavigation")
                        .WithMany("DetailsNavigation")
                        .HasForeignKey("Idregroupement")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_drg_rgp");

                    b.HasOne("SAE401_API.Models.EntityFramework.Coloration", "ColorationsNavigation")
                        .WithMany("DetailRegroupementNavigation")
                        .HasForeignKey("Idproduit", "Idcouleur")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_drg_col");

                    b.Navigation("ColorationsNavigation");

                    b.Navigation("RegroupementNavigation");
                });

            modelBuilder.Entity("SAE401_API.Models.EntityFramework.Historiqueconsultation", b =>
                {
                    b.HasOne("SAE401_API.Models.EntityFramework.Client", "ClientNavigation")
                        .WithMany("HistoriquesNavigation")
                        .HasForeignKey("Idclient")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_hst_cli");

                    b.HasOne("SAE401_API.Models.EntityFramework.Produit", "ProduitNavigation")
                        .WithMany("HistoriquesNavigation")
                        .HasForeignKey("Idproduit")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_hst_prd");

                    b.Navigation("ClientNavigation");

                    b.Navigation("ProduitNavigation");
                });

            modelBuilder.Entity("SAE401_API.Models.EntityFramework.Messagechatbot", b =>
                {
                    b.HasOne("SAE401_API.Models.EntityFramework.Client", "ClientNavigation")
                        .WithMany("MessagesNavigation")
                        .HasForeignKey("Idclient")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_msg_cli");

                    b.Navigation("ClientNavigation");
                });

            modelBuilder.Entity("SAE401_API.Models.EntityFramework.Paiement", b =>
                {
                    b.HasOne("SAE401_API.Models.EntityFramework.Cartebancaire", "CarteNavigation")
                        .WithMany("PaiementsNavigation")
                        .HasForeignKey("Idcartebancaire")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_pmt_car");

                    b.HasOne("SAE401_API.Models.EntityFramework.Commande", "CommandeNavigation")
                        .WithMany("PaiementsNavigation")
                        .HasForeignKey("Idcommande")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_pmt_cmd");

                    b.HasOne("SAE401_API.Models.EntityFramework.Typepaiement", "TypeNavigation")
                        .WithMany("PaiementsNavigation")
                        .HasForeignKey("Idtypepaiement")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_pmt_tpm");

                    b.Navigation("CarteNavigation");

                    b.Navigation("CommandeNavigation");

                    b.Navigation("TypeNavigation");
                });

            modelBuilder.Entity("SAE401_API.Models.EntityFramework.Photoavi", b =>
                {
                    b.HasOne("SAE401_API.Models.EntityFramework.Avisproduit", "AviNavigation")
                        .WithMany("PhotoavisNavigation")
                        .HasForeignKey("Idavis")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_pav_avi");

                    b.HasOne("SAE401_API.Models.EntityFramework.Photo", "PhotoNavigation")
                        .WithMany("PhotoavisNavigation")
                        .HasForeignKey("Idphoto")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_pav_pho");

                    b.Navigation("AviNavigation");

                    b.Navigation("PhotoNavigation");
                });

            modelBuilder.Entity("SAE401_API.Models.EntityFramework.Photocoloration", b =>
                {
                    b.HasOne("SAE401_API.Models.EntityFramework.Photo", "PhotoNavigation")
                        .WithMany("PhotocolsNavigation")
                        .HasForeignKey("Idphoto")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_pco_pho");

                    b.HasOne("SAE401_API.Models.EntityFramework.Coloration", "ColorationNavigation")
                        .WithMany("PhotocolsNavigation")
                        .HasForeignKey("Idproduit", "Idcouleur")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_pco_col");

                    b.Navigation("ColorationNavigation");

                    b.Navigation("PhotoNavigation");
                });

            modelBuilder.Entity("SAE401_API.Models.EntityFramework.Produit", b =>
                {
                    b.HasOne("SAE401_API.Models.EntityFramework.Pay", "PayNavigation")
                        .WithMany("ProduitsNavigation")
                        .HasForeignKey("Idpays")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_prd_pay");

                    b.HasOne("SAE401_API.Models.EntityFramework.Typeproduit", "TypeNavigation")
                        .WithMany("ProduitsNavigation")
                        .HasForeignKey("Idtypeproduit")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_prd_tpd");

                    b.Navigation("PayNavigation");

                    b.Navigation("TypeNavigation");
                });

            modelBuilder.Entity("SAE401_API.Models.EntityFramework.Produitsimilaire", b =>
                {
                    b.HasOne("SAE401_API.Models.EntityFramework.Produit", "ProduitRefNavigation")
                        .WithMany("SimilaireRefNavigation")
                        .HasForeignKey("IdproduitRef")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_dps_prd");

                    b.HasOne("SAE401_API.Models.EntityFramework.Produit", "ProduitSimNavigation")
                        .WithMany("SimilaireSimNavigation")
                        .HasForeignKey("IdproduitSim")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_dps_prd2");

                    b.Navigation("ProduitRefNavigation");

                    b.Navigation("ProduitSimNavigation");
                });

            modelBuilder.Entity("SAE401_API.Models.EntityFramework.Professionel", b =>
                {
                    b.HasOne("SAE401_API.Models.EntityFramework.Activitepro", "ActiviteproNavigation")
                        .WithMany("ProfessionelsNavigation")
                        .HasForeignKey("Idactivitepro")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_pro_act");

                    b.HasOne("SAE401_API.Models.EntityFramework.Client", "ClientNavigation")
                        .WithOne("ProfessionelNavigation")
                        .HasForeignKey("SAE401_API.Models.EntityFramework.Professionel", "Idclient")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_pro_cli");

                    b.Navigation("ActiviteproNavigation");

                    b.Navigation("ClientNavigation");
                });

            modelBuilder.Entity("SAE401_API.Models.EntityFramework.Signalementavi", b =>
                {
                    b.HasOne("SAE401_API.Models.EntityFramework.Avisproduit", "AviNavigation")
                        .WithMany("SignalementsNavigation")
                        .HasForeignKey("Idavis")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_sga_avi");

                    b.HasOne("SAE401_API.Models.EntityFramework.Typesignalement", "TypeNavigation")
                        .WithMany("SignalementsNavigation")
                        .HasForeignKey("Idtypesignalement")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_sga_tsg");

                    b.Navigation("AviNavigation");

                    b.Navigation("TypeNavigation");
                });

            modelBuilder.Entity("SAE401_API.Models.EntityFramework.Typeproduit", b =>
                {
                    b.HasOne("SAE401_API.Models.EntityFramework.Categorieproduit", "CategorieNavigation")
                        .WithMany("TypesNavigation")
                        .HasForeignKey("Idcategorie")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_tpd_cat");

                    b.Navigation("CategorieNavigation");
                });

            modelBuilder.Entity("SAE401_API.Models.EntityFramework.Valeurattribut", b =>
                {
                    b.HasOne("SAE401_API.Models.EntityFramework.Attributproduit", "AttributNavigation")
                        .WithMany("ValeursNavigation")
                        .HasForeignKey("Idattribut")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_val_att");

                    b.HasOne("SAE401_API.Models.EntityFramework.Produit", "ProduitNavigation")
                        .WithMany("ValeursNavigation")
                        .HasForeignKey("Idproduit")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_val_prd");

                    b.Navigation("AttributNavigation");

                    b.Navigation("ProduitNavigation");
                });

            modelBuilder.Entity("SAE401_API.Models.EntityFramework.Activitepro", b =>
                {
                    b.Navigation("ProfessionelsNavigation");
                });

            modelBuilder.Entity("SAE401_API.Models.EntityFramework.Adresse", b =>
                {
                    b.Navigation("CommandeFactNavigation");

                    b.Navigation("CommandeLivrNavigation");
                });

            modelBuilder.Entity("SAE401_API.Models.EntityFramework.Attributproduit", b =>
                {
                    b.Navigation("ValeursNavigation");
                });

            modelBuilder.Entity("SAE401_API.Models.EntityFramework.Avisproduit", b =>
                {
                    b.Navigation("PhotoavisNavigation");

                    b.Navigation("SignalementsNavigation");
                });

            modelBuilder.Entity("SAE401_API.Models.EntityFramework.Cartebancaire", b =>
                {
                    b.Navigation("PaiementsNavigation");
                });

            modelBuilder.Entity("SAE401_API.Models.EntityFramework.Categorieproduit", b =>
                {
                    b.Navigation("CategorieEnfanteNavigation");

                    b.Navigation("TypesNavigation");
                });

            modelBuilder.Entity("SAE401_API.Models.EntityFramework.Client", b =>
                {
                    b.Navigation("AdressesNavigation");

                    b.Navigation("AimesNavigation");

                    b.Navigation("AvisNavigation");

                    b.Navigation("CartesNavigation");

                    b.Navigation("CodesNavigation");

                    b.Navigation("CommandesNavigation");

                    b.Navigation("HistoriquesNavigation");

                    b.Navigation("MessagesNavigation");

                    b.Navigation("PaniersCompositionNavigation");

                    b.Navigation("PaniersProduitNavigation");

                    b.Navigation("ProfessionelNavigation");
                });

            modelBuilder.Entity("SAE401_API.Models.EntityFramework.Codepromo", b =>
                {
                    b.Navigation("CommandesNavigation");
                });

            modelBuilder.Entity("SAE401_API.Models.EntityFramework.Coloration", b =>
                {
                    b.Navigation("DetailRegroupementNavigation");

                    b.Navigation("DetailsCommandeNavigation");

                    b.Navigation("DetailsCompositionNavigation");

                    b.Navigation("DetailsPanierNavigation");

                    b.Navigation("PhotocolsNavigation");
                });

            modelBuilder.Entity("SAE401_API.Models.EntityFramework.Commande", b =>
                {
                    b.Navigation("DetailsCompositionNavigation");

                    b.Navigation("DetailsProduitNavigation");

                    b.Navigation("PaiementsNavigation");
                });

            modelBuilder.Entity("SAE401_API.Models.EntityFramework.Compositionproduit", b =>
                {
                    b.Navigation("CommandesNavigation");

                    b.Navigation("DetailsNavigation");

                    b.Navigation("PaniersNavigation");
                });

            modelBuilder.Entity("SAE401_API.Models.EntityFramework.Couleur", b =>
                {
                    b.Navigation("ColorationsNavigation");
                });

            modelBuilder.Entity("SAE401_API.Models.EntityFramework.Departement", b =>
                {
                    b.Navigation("AdressesNavigation");
                });

            modelBuilder.Entity("SAE401_API.Models.EntityFramework.Pay", b =>
                {
                    b.Navigation("AdressesNavigation");

                    b.Navigation("ProduitsNavigation");
                });

            modelBuilder.Entity("SAE401_API.Models.EntityFramework.Photo", b =>
                {
                    b.Navigation("CategoriesNavigation");

                    b.Navigation("PhotoavisNavigation");

                    b.Navigation("PhotocolsNavigation");
                });

            modelBuilder.Entity("SAE401_API.Models.EntityFramework.Produit", b =>
                {
                    b.Navigation("AimesNavigation");

                    b.Navigation("AvisNavigation");

                    b.Navigation("ColorationsNavigation");

                    b.Navigation("HistoriquesNavigation");

                    b.Navigation("SimilaireRefNavigation");

                    b.Navigation("SimilaireSimNavigation");

                    b.Navigation("ValeursNavigation");
                });

            modelBuilder.Entity("SAE401_API.Models.EntityFramework.Regroupementproduit", b =>
                {
                    b.Navigation("DetailsNavigation");
                });

            modelBuilder.Entity("SAE401_API.Models.EntityFramework.Statutcommande", b =>
                {
                    b.Navigation("CommandesNavigation");
                });

            modelBuilder.Entity("SAE401_API.Models.EntityFramework.Transporteur", b =>
                {
                    b.Navigation("CommandesNavigation");
                });

            modelBuilder.Entity("SAE401_API.Models.EntityFramework.Typepaiement", b =>
                {
                    b.Navigation("PaiementsNavigation");
                });

            modelBuilder.Entity("SAE401_API.Models.EntityFramework.Typeproduit", b =>
                {
                    b.Navigation("AttributsNavigation");

                    b.Navigation("ProduitsNavigation");
                });

            modelBuilder.Entity("SAE401_API.Models.EntityFramework.Typesignalement", b =>
                {
                    b.Navigation("SignalementsNavigation");
                });

            modelBuilder.Entity("SAE401_API.Models.EntityFramework.Ville", b =>
                {
                    b.Navigation("AdressesNavigation");
                });
#pragma warning restore 612, 618
        }
    }
}
